### ISSUE TITLE
Screenshots on failure feature?

### ISSUE THREAD

**Issue by thebarty** [sandcastle/mocha-circleci-reporter#5]
Hi guys,

thanks a lot for this great package. Right from the start it works like a charm - even locally in development mode. Thanks a lot!! 👍 

I am wondering if you guys could add screenshot-support on-failure, which would be really handy to have. The best package I have found so far is: https://github.com/rluba/mocha-proshot. I tried to set it up manually with circle-ci but could not get it running. 

**Maybe you guys have more luck and can include it (or an alternative) in this setup?**

**Comment by bf4** [comment]
@thebarty I'm not sure that adding a screenshot on failure should be part of a report formatter.  How would this be a natural fit for this library, as opposed to it's own thing?

**Comment by sandcastle** [comment]
@thebarty thanks for the kind words. I have to agree with @bf4 this doesn't really belong within this package. Anything protractor specific should be in a separate library, I would suggest forking this repo (it's MIT) and blending in the parts of the other repo that you need.

The [source](https://github.com/rluba/mocha-proshot/blob/master/index.js) looks quite simple in the repo you have mentioned. I'm quite short on time at the moment, but if you want to get started I might be able to help out if you get stuck on anything - just tag me into any issues within the repo.
